# For details on schedule statements, see here: https://godoc.org/github.com/robfig/cron
plugins:
  pkg_compliance:
    cmd: pkg_compliance
    schedule: "@hourly"
    url: "http://example.com/plugins/pkg_compliance"
  computer_info:
    cmd: computer_info
    schedule: "@every 1m"
