asset:
  id: "000006913-evil-and-bad-for-you"
customer:
  id: "00006913"
plugins:
  pkg_compliance:
    cmd: pkg_compliance
    schedule: "@hourly"
    url: "http://example.com/plugins/pkg_compliance"
  computer_info:
    cmd: computer_info
    schedule: "@every 1m"
